name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  main:
    uses: bsm/misc/.github/workflows/build-push-ghcr.yml@main
    with:
      image: ${{ github.repository }}/console
      tags: |
        type=raw,value=latest,enable={{is_default_branch}}
